services:
  telegram_media:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logging
    command: python main.py
    restart: unless-stopped

  chatgpt_bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logging
    command: python Assistant.py
    restart: unless-stopped

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: unless-stopped
